openapi: 3.0.0
x-stoplight:
  id: ol8z5ia9supyu
info:
  title: Task Management API
  version: 1.0.0
  description: Task Management API
paths:
  /v1/users:
    post:
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/User'
                - $ref: '#/components/schemas/Credential'
      responses:
        '201':
          description: |
            Created
          headers: {}
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Conflict
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: User registration
      operationId: postV1Users
      description: User registration
      parameters: []
      security: []
      tags:
        - users
  /v1/users/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credential'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/UserId'
                  - $ref: '#/components/schemas/User'
          headers:
            Set-Cookie:
              description: Cookie to store the JWT token
              schema:
                type: string
                example: "jwt=jwt_token; HttpOnly; Secure; SameSite=Strict;"
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: User login
      operationId: postV1UsersLogin
      description: |-
        Logs in a registered user. 
        Returns a JWT on success.
      parameters: []
      security: []
      tags:
        - users
  /v1/tasks:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskWithDescription'
        required: true
      responses:
        '201':
          description: Created
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 'Unauthorized, invalid JWT token'
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: Create task
      operationId: postV1tTasks
      description: Create task
      security:
        - bearerAuth: []
      tags:
        - tasks
    get:
      parameters:
        - name: assignee_ids
          schema:
            type: array
            items:
              type: string
          in: query
          description: Assignee ids
        - name: status
          schema:
            type: string
            enum:
              - not_started
              - in_progress
              - completed
          in: query
          description: Status
        - name: priority
          schema:
            type: string
            enum:
              - low
              - medium
              - high
          in: query
          description: Priority
        - name: expires
          schema:
            type: string
            enum:
              - lt
              - gt
          in: query
          description: Deadline
        - name: sort_by
          schema:
            type: string
            enum:
              - asc
              - desc
          in: query
          description: Sort order
        - name: cursor
          schema:
            type: string
          in: query
          description: Cursor
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      allOf:
                        - $ref: '#/components/schemas/TaskId'
                        - $ref: '#/components/schemas/Task'
                  pagination:
                    type: object
                    properties:
                      next_cursor:
                        type: string
                        nullable: true
                      previous_cursor:
                        type: string
                        nullable: true
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 'Unauthorized, invalid JWT token'
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: Get task list
      operationId: getV1Tasks
      description: Get task list
      security:
        - bearerAuth: []
      tags:
        - tasks
  '/v1/tasks/{taskId}':
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskWithDescription'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: Get task
      operationId: getV1TasksId
      description: Get task details
      tags:
        - tasks
      security:
        - bearerAuth: []
    put:
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Task'
                - $ref: '#/components/schemas/TaskDescription'
        required: true
      responses:
        '204':
          description: No Content
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 'Unauthorized, invalid JWT token'
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Update task
      operationId: putV1TasksId
      description: Update task
      security:
        - bearerAuth: []
      tags:
        - tasks
    delete:
      responses:
        '204':
          description: No Content
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 'Unauthorized, invalid JWT token'
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: Delete task
      operationId: deleteTasksId
      description: Delete task
      security:
        - bearerAuth: []
      tags:
        - tasks
    parameters:
      - schema:
          type: string
          format: uuid
        name: taskId
        in: path
        required: true
        description: Task ID
components:
  schemas:
    Credential:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          description: Email
          format: email
        password:
          type: string
          description: Password
          minLength: 8
          maxLength: 24
      x-internal: false
    UserId:
      type: object
      required:
        - user_id
      properties:
        user_id:
          description: User ID
          type: string
          format: uuid
      x-internal: false
    User:
      type: object
      required:
        - name
      properties:
        name:
          description: User name
          type: string
          maxLength: 50
      x-internal: false
    TaskId:
      type: object
      required:
        - task_id
      properties:
        task_id:
          description: Task ID
          type: string
          format: uuid
      x-internal: false
    Task:
      type: object
      title: Task
      x-internal: false
      required:
        - assignee_ids
        - title
        - priority
        - status
        - begins_at
        - ends_at
      properties:
        assignee_ids:
          description: Assignee IDs
          type: array
          items:
            $ref: '#/components/schemas/UserId'
        title:
          description: Task name
          type: string
        priority:
          enum:
            - low
            - medium
            - high
          description: Priority
        status:
          enum:
            - not_started
            - in_progress
            - completed
          description: Task Progress
        begins_at:
          format: date-time
          description: Start date and time
          type: string
        ends_at:
          format: date-time
          description: End date and time
          type: string
    TaskDescription:
      type: object
      x-internal: false
      properties:
        text:
          type: string
          nullable: true
    TaskWithDescription:
      title: ''
      allOf:
        - $ref: '#/components/schemas/Task'
        - $ref: '#/components/schemas/TaskDescription'
    Error:
      type: object
      properties:
        code:
          description: error code
          type: integer
        message:
          description: error message
          type: string
      x-internal: false
  responses: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT returned when user login is successful
tags:
  - name: users
  - name: tasks
